### ISSUE TITLE
Unable to boot mainline ArchLinuxARM with this

### ISSUE THREAD

**Issue by somini** [matyas1995/u-boot-PKGBUILD#1]
Thanks for sharing this in a easily digestible state.

I followed this to a T and I'm unable to boot my RockPro64. I can hear the disks spinning but I don't get any HDMI output nor DHCP traffic. Do you have a ballpark of the required time during first boot to generate SSH keys for example?

I downloaded the latest armv8 tarball from here: https://archlinuxarm.org/platforms/armv8/generic

When did you download the latest ALARM tarball from the site? What's the kernel version? Are you using the PCI adapter, can this be an issue?

Thanks anyway.

**Comment by somini** [comment]
BTW, I'm *almost* sure this is not an hardware issue, because I can boot the ayufan debian images. 

https://forum.pine64.org/showthread.php?tid=7645

I REALLY wanted to remain on Arch for consistency, but I have been tearing my hair for a few weeks now.

**Comment by matyas1995** [comment]
Hello,

Booting time is under 30s for me. The time of downloading images is the time of writing of the blogpost, so about a week old.

There could be about a million reasons why you have problems, so I would absolutely recommend you to start looking at your serial UART and at the boot messages, including the bootloader messages there instead of waiting for the HDMI. If you have looked at the forums concerning HDMI output, especially on unpatched mainline kernels like you are trying to use, that would be the last thing you would be relying on for debug output. You are not on an x86, where already the BIOS has display support for fancy error messages.

Yes, I am not only using the PCI adapter, I have a raid set up from 4 disks with the rootfs residing there. I use the SD card only to keep the kernel and the bootloader there.

So, go and get your UART transceiver out and start looking at the boot messages. The RockPro and U-Boot are a fine couple, they will tell you whats wrong real quick. Chances are you just mistyped the entries in you bootloader config and have been sitting around with your board screaming "rootfs not found" oer the UART.

**Comment by somini** [comment]
I forgot to order the UART transceiver when ordering all the other hardware, so I was just trying to debug this "blindly", but it doesn't cut it anymore. I'll just bite the bullet and order that now, I guess.

> Chances are you just mistyped the entries in you bootloader config and have been sitting around with your board screaming "rootfs not found" over the UART.

This is highly likely. :grin: 

Thanks for that, I will close this.
